version: '3'
services:
  app:
    build: .
    container_name: proxycat
    ports:
      - "1080:1080"
    volumes:
      - ./config:/app/config
    restart: unless-stopped
    network_mode: "bridge"
