version: '3'
services:
  proxycat:
    build: .
    environment:
      - TZ=Asia/Shanghai
    ports:
      - "1080:1080"
      - "5000:5000"
    volumes:
      - ./config:/app/config
    restart: unless-stopped
    network_mode: "bridge"